# Configuración base de Serenity
serenity.project.name=ProyectoAppiumChrome
serenity.take.screenshots=FOR_FAILURES
serenity.logging=VERBOSE

# URL del servidor Appium
appium.hub=http://127.0.0.1:4723/wd/hub

# Capabilities de Appium
appium.platformName=Android
appium.deviceName=emulator-5554
appium.automationName=UiAutomator2
appium.platformVersion=15.0
appium.appPackage=com.android.chrome
appium.appActivity=com.google.android.apps.chrome.Main

# Lanzar navegador Chrome
appium.browserName=Chrome

# Auto aceptar permisos
appium.autoGrantPermissions=true

# No reinstalar apps si no es necesario
appium.noReset=true
appium.fullReset=false

# Si deseas usar un ChromeDriver específico:
# appium.chromedriverExecutable=/ruta/completa/a/chromedriver
